app:
  port: ":8000"
raven:
  dsn: "http://a67ba0e71d9a4d7b82eaaa7cd642adfd@localhost:9000/2"
logging:
  level: debug
  encoding: console
  outputPaths:
    - stdout
    - /tmp/log/fdnsvc.log
  errorOutputPaths:
    - stderr
    - /tmp/log/fdnsvc-err.log
  initialFields:
    appName : fdnsvc
  encoderConfig:
    messageKey: message
    levelKey : level
    levelEncoder: lowercase